### PR TITLE
added fr.lproj

### PR DESCRIPTION
**Pull request by Balackburn**

### CODE REVIEW

**Comment by Balackburn** [comment]
@arichorn @PoomSmart banned me from all its Githubs repos after I submitted PRs for French translations in several of its repos.

I'm not in your drama and he refused all my PRs even though they were perfectly valid just because I was associated with you, this childish stuff really pisses me off.

**Comment by arichornlover** [comment]
> I'm not in your drama and he refused all my PRs even though they were perfectly valid just because I was associated with you, this childish stuff really pisses me off.

I’m sorry about that Balackburn. I’ve messed up a few times a couple months ago and got banned and I’m really sorry that I can be immature in some cases but it sucks that he banned you. but look. You’ve done a great job Balackburn with all of the things you’ve done though, I even helped out.. and about the Drama. That stuff just sucks and in some cases it is best to ignore that type of stuff like what I’m doing, . I know you might not give me a chance but I did my best to do better and actually be useful for the community. And at least made some stuff like LowContrastMode, VersionSpoofer & some other stuff that I made. and about PoomSmart, he’s a great tweak developer but I just don’t suggest interacting like how I messed up. Overrall I’m so sorry about the childish about the childish stuff. I’m pissed off about it too.

**Comment by Balackburn** [comment]
@arichorn I'm not angry with you and I thank you for all the help you've given me, I just wanted to help by translating 5-6 tweaks into French (my native language) it took time and was for nothing as it was rejected and got me banned, this is childish from @Poomsmart part but it's is tweaks he do what he want.

He also said "Are you the delinquent reincarnated?" I think he thought I was you using an alt account, you're doing a great job for the community, keep up the good work.

**Comment by arichornlover** [comment]
> @arichorn I'm not angry with you and I thank you for all the help you've given me, I just wanted to help by translating 5-6 tweaks into French (my native language) it took time and was for nothing as it was rejected and got me banned, this is childish from @PoomSmart part but it's is tweaks he do what he want.

I don’t understand Fr, and yeah those are PoomSmart’s tweaks, I like his work but I don’t usually do pull requests on them but in some cases I usually only do pull requests if I’m there to just fix English localization spelling errors or pull requests that includes a patch to fix the tweak. (Like I did for this for example https://github.com/MiRO92/YTNoShorts/pull/2)

> He also said "Are you the delinquent reincarnated?" I think he thought I was you using an alt account

that’s strange I don’t own an alt account. And also it should’ve been obvious that it wasn’t me. I’m really sorry about him doing that to you. I feel really bad he did that to you.

> you're doing a great job for the community, keep up the good work.

Thanks Balackburn! You’ve done a good job aswell too!

**Comment by arichornlover** [comment]
And hey Balackburn, you can use the forked versions of the tweaks if you want to use the French localization. Sometimes I have to do it if my pull request gets rejected even if it’s a helpful one, I also will accept the pull request here if you like!
https://github.com/arichorn/YTNoCommunityPosts/
and since PoomSmart Sadly banned you, I’m gonna add the fr.lproj to all of my other tweaks that uses localization

**Pull request merged**
